version: "3.3"

services:
  rdp:
    build:
      context: ./rdp
      dockerfile: Dockerfile
    networks:
      - oipa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - .:/home/ubuntu/src/v10
      - ssh:/home/ubuntu/.ssh
      - scratch:/home/ubuntu/scratch:Z
      - git:/home/ubuntu/git
    ports:
      - 3389:3389

volumes:
  ssh:
  scratch:
  git:

networks:
  oipa:
    external: true
